---
# This playbook deploys the entire setup for the Raspberry Pi host
- hosts: derek
  vars_files:
    - secrets.yml
  roles:
    - {role: 'common', tags: 'common'}
    - {role: 'motd', tags: 'motd'}
    - {role: 'yatesr.timezone', tags: 'timezone'}
    - {role: 'docker', tags: 'docker'}
